### ISSUE TITLE
New es_extended doesn't support

### ISSUE THREAD

**Issue by nassTEAman** [Elipse458/el_business#4]
The new es_extended doesn't support the scripts. Whenever you put it in it just doesn't show the marker.

**Comment by Elipse458** [comment]
i dont have much time rn so ill be able to fix this in a few days

**Comment by nassTEAman** [comment]
Great Thanks

**Comment by nassTEAman** [comment]
> i dont have much time rn so ill be able to fix this in a few days

Just let me know when you finish it

**Comment by Elipse458** [comment]
update released
