### ISSUE TITLE
Limit amount of businesses players can own

### ISSUE THREAD

**Issue by Tiimon** [Elipse458/el_business#5]
I think it would be nice to have a feature for setting the maximum amount of businesses a player could own in the config, such as:
`Config.MaxBusiness = 2` 
This would allow the player to own no more than two businesses on the server, making it so one player doesn't go around buying all the businesses up.

**Comment by Elipse458** [comment]
will do and will keep this open so i don't forget

**Comment by Elipse458** [comment]
after a bit of fighting with github i released the update, enjoy
